sudo: required

language: node_js

node_js:
  - stable

before_install:
  - npm install gitbook-cli -g
  - gitbook fetch 3.2.3

before_deploy:
  - tar czvf book_html.tar.gz content/_book/

jobs:
  include:
    script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 88005b5972c8b473acef2f6174acfe382c93ee90  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

after_success:
  - ls -lh

branches:
  only:
  - master